-- CreateEnum
CREATE TYPE "BookingStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');

-- CreateTable
CREATE TABLE "booking_requests" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "lineUserId" TEXT,
    "createdById" TEXT,
    "requesterName" TEXT,
    "contactPhone" TEXT,
    "departmentId" INTEGER,
    "venueId" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "attendees" INTEGER NOT NULL,
    "status" "BookingStatus" NOT NULL DEFAULT 'PENDING',
    "rejectReason" TEXT,
    "firstStartAt" TIMESTAMP(3) NOT NULL,
    "lastEndAt" TIMESTAMP(3) NOT NULL,
    "approvedById" TEXT,
    "approvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "booking_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "booking_slots" (
    "id" TEXT NOT NULL,
    "bookingRequestId" TEXT NOT NULL,
    "venueId" TEXT NOT NULL,
    "startAt" TIMESTAMP(3) NOT NULL,
    "endAt" TIMESTAMP(3) NOT NULL,
    "isCancelled" BOOLEAN NOT NULL DEFAULT false,
    "cancelledAt" TIMESTAMP(3),
    "cancelledById" TEXT,
    "cancelledByRole" TEXT,
    "cancelReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "booking_slots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app_settings" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "app_settings_pkey" PRIMARY KEY ("key")
);

-- CreateIndex
CREATE UNIQUE INDEX "booking_requests_code_key" ON "booking_requests"("code");

-- CreateIndex
CREATE INDEX "booking_requests_lineUserId_idx" ON "booking_requests"("lineUserId");

-- CreateIndex
CREATE INDEX "booking_requests_createdById_idx" ON "booking_requests"("createdById");

-- CreateIndex
CREATE INDEX "booking_requests_venueId_idx" ON "booking_requests"("venueId");

-- CreateIndex
CREATE INDEX "booking_requests_status_idx" ON "booking_requests"("status");

-- CreateIndex
CREATE INDEX "booking_requests_firstStartAt_lastEndAt_idx" ON "booking_requests"("firstStartAt", "lastEndAt");

-- CreateIndex
CREATE INDEX "booking_slots_venueId_startAt_endAt_idx" ON "booking_slots"("venueId", "startAt", "endAt");

-- CreateIndex
CREATE INDEX "booking_slots_bookingRequestId_idx" ON "booking_slots"("bookingRequestId");

-- CreateIndex
CREATE INDEX "booking_slots_isCancelled_idx" ON "booking_slots"("isCancelled");

-- AddForeignKey
ALTER TABLE "booking_requests" ADD CONSTRAINT "booking_requests_lineUserId_fkey" FOREIGN KEY ("lineUserId") REFERENCES "line_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_requests" ADD CONSTRAINT "booking_requests_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "system_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_requests" ADD CONSTRAINT "booking_requests_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_requests" ADD CONSTRAINT "booking_requests_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "venues"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_requests" ADD CONSTRAINT "booking_requests_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "system_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_slots" ADD CONSTRAINT "booking_slots_bookingRequestId_fkey" FOREIGN KEY ("bookingRequestId") REFERENCES "booking_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_slots" ADD CONSTRAINT "booking_slots_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "venues"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ┌────────────────────────────────────────────────────────────────────────────────────────────┐
-- │ HAND-WRITTEN BELOW THIS LINE — not generated by Prisma Migrate, and not re-generable.       │
-- │ PSL cannot express a CHECK constraint or a data seed, so both live here. If this migration  │
-- │ is ever regenerated from the schema, these two blocks must be carried over by hand.         │
-- └────────────────────────────────────────────────────────────────────────────────────────────┘

-- The dual-origin ownership invariant (D-C18, PO 2026-09-02).
--
-- Both `lineUserId` (the LIFF requester) and `createdById` (the staff member who created the booking
-- from the Admin Portal) are nullable, because each origin populates only its own column. But a row
-- with NEITHER belongs to nobody: it cannot be listed on the user's My Bookings screen, cannot be
-- notified, and cannot be audited.
--
-- It is enforced HERE and not in a service method for the reason ADR-001 gives: an invariant a code
-- path can forget to call is not an invariant. Same standard the double-booking rule is held to.
--
-- ⚠️ This is OR, not XOR, deliberately. Both columns may be set at once — that is staff booking ON
-- BEHALF OF a LINE user who does have an account: `createdById` is who typed it, `lineUserId` is
-- whose booking it is, and the row must still appear in that user's list.
--
-- ⚠️ Column names are camelCase and quoted. Live columns in this schema carry no @map, so the
-- physical names are "lineUserId" / "createdById" — never line_user_id / created_by_id.
ALTER TABLE "booking_requests"
    ADD CONSTRAINT "booking_requests_owner_check"
    CHECK (("lineUserId" IS NOT NULL) OR ("createdById" IS NOT NULL));

-- Seed the one setting the booking domain needs from day one (Q-C4 sub-ruling ①).
--
-- Seeded in the MIGRATION rather than in a scripts/seed-*.ts, unlike the option lists: those are
-- vocabularies an operator curates and re-seeds, this is a value the cancel endpoint DEREFERENCES on
-- every call. A backend deployed against a migrated database must never find this row missing.
--
-- The admin screen to edit it does not exist yet (CLIENT-SETTINGS-1, undesigned). Reading the table
-- with a documented default from day one is what stops that screen's arrival from being a rework.
--
-- 🔴 Enforced SERVER-SIDE. The client reads this value to enable a button and to word an
-- explanation; a disabled button is UX, never an authorisation boundary.
INSERT INTO "app_settings" ("key", "value", "description", "createdAt", "updatedAt")
VALUES (
    'booking.cancel_lead_minutes',
    '30',
    'Cancellation lead time threshold in minutes',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("key") DO NOTHING;
