-- CreateTable
CREATE TABLE "venue_types" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "isSystemReserved" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "venue_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "amenities" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "amenities_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "venue_types_deletedAt_idx" ON "venue_types"("deletedAt");

-- CreateIndex
CREATE INDEX "amenities_deletedAt_idx" ON "amenities"("deletedAt");

-- ── HAND-WRITTEN: PARTIAL unique indexes on the ACTIVE name ──────────────────
-- Not generated by Prisma, and they cannot be: the PSL has no way to express a
-- WHERE clause on an index, so `@unique` would span soft-deleted rows and burn a
-- name forever. That is right for `system_users.email` (a deleted address must
-- never be re-claimable) and wrong here — deleting `โรงยิม` must leave the name
-- free to use again. Same construction as `departments_name_active_key` and
-- `personnel_roles_name_active_key` in the init migration; keep the naming so the
-- four read as one family.
--
-- The service relies on these existing: create/rename catch Prisma's P2002 from
-- exactly this index and map it to a 409. Drop the index and the 409 silently
-- becomes a duplicate row.
CREATE UNIQUE INDEX "venue_types_name_active_key" ON "venue_types"("name") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "amenities_name_active_key" ON "amenities"("name") WHERE "deletedAt" IS NULL;

-- ⚠️ NO INSERT IN THIS FILE, DELIBERATELY (`Q16`, 2026-08-25). Migrations here are
-- DDL-only; the tombstone row `ไม่พบประเภทสถานที่` and the five starting categories
-- are written by `npm run venue-types:seed`, which is idempotent and re-runnable.
-- Until it is run, DELETE /venue-types/:id answers 500 TOMBSTONE_ROW_MISSING —
-- loud, honest, and non-destructive, and exactly the state /departments is in on a
-- database where `auth:create-superadmin` has never run.
