-- AlterTable
ALTER TABLE "booking_slots" ADD COLUMN     "holdsSlot" BOOLEAN NOT NULL DEFAULT false;

-- ┌────────────────────────────────────────────────────────────────────────────────────────────┐
-- │ HAND-WRITTEN BELOW THIS LINE — not generated by Prisma Migrate, and not re-generable.       │
-- │ PSL cannot express an extension, a trigger or an EXCLUDE constraint. If this migration is   │
-- │ ever regenerated from the schema, every block below must be carried over by hand.           │
-- └────────────────────────────────────────────────────────────────────────────────────────────┘

-- ① btree_gist. The GiST operator class for `=` on a plain scalar ("venueId" TEXT) lives in this
-- extension; core GiST only knows the range operators. Without it the constraint below fails with
-- "data type text has no default operator class for access method gist".
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ② BACKFILL, BEFORE THE CONSTRAINT EXISTS.
-- Dev and staging databases have carried booking rows since 2026-09-02 (the client portal shipped on
-- 09-03). `DEFAULT false` is already correct for PENDING / REJECTED / CANCELLED rows and for every
-- cancelled slot; only live slots of APPROVED requests need flipping. Doing this AFTER the
-- ADD CONSTRAINT would validate an all-false column and prove nothing.
UPDATE "booking_slots" s
   SET "holdsSlot" = true
  FROM "booking_requests" r
 WHERE r."id" = s."bookingRequestId"
   AND r."status" = 'APPROVED'
   AND s."isCancelled" = false;

-- ③ THE DATABASE IS THE ONLY WRITER OF "holdsSlot" (see the column's doc comment in schema.prisma).
--
-- BEFORE, not AFTER, and it assigns NEW unconditionally: that is what makes the column impossible to
-- disagree with its sources. A value supplied by Prisma, by psql or by Studio is overwritten here.
CREATE OR REPLACE FUNCTION "booking_slots_holds_slot"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW."holdsSlot" := (NOT NEW."isCancelled")
    AND EXISTS (
      SELECT 1 FROM "booking_requests" r
       WHERE r."id" = NEW."bookingRequestId"
         AND r."status" = 'APPROVED'
    );
  RETURN NEW;
END;
$$;

CREATE TRIGGER "booking_slots_holds_slot_biu"
BEFORE INSERT OR UPDATE ON "booking_slots"
FOR EACH ROW EXECUTE FUNCTION "booking_slots_holds_slot"();

-- ④ The parent side. A status flip changes the answer for every child, and the children are not
-- touched by that UPDATE — so the parent has to push it.
--
-- `AFTER UPDATE OF "status"` fires whenever the column is named in the SET list (even if unchanged),
-- which is why the IS DISTINCT FROM guard is here rather than being a comment. The UPDATE below
-- re-fires trigger ③ on each child, which recomputes the same value from the already-updated parent
-- row — consistent, and cheap enough at <= 60 children per request.
--
-- ⚠️ THIS IS THE STATEMENT THAT RAISES 23P01 ON A DOUBLE BOOKING. Approving a request is an UPDATE of
-- `booking_requests`; the exclusion violation surfaces from that statement, not from a write the
-- service made against `booking_slots`. Anyone reading a stack trace should expect that.
CREATE OR REPLACE FUNCTION "booking_requests_holds_slot"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."status" IS DISTINCT FROM OLD."status" THEN
    UPDATE "booking_slots" s
       SET "holdsSlot" = (NOT s."isCancelled") AND (NEW."status" = 'APPROVED')
     WHERE s."bookingRequestId" = NEW."id"
       AND s."holdsSlot" IS DISTINCT FROM ((NOT s."isCancelled") AND (NEW."status" = 'APPROVED'));
  END IF;
  RETURN NULL;
END;
$$;

CREATE TRIGGER "booking_requests_holds_slot_au"
AFTER UPDATE OF "status" ON "booking_requests"
FOR EACH ROW EXECUTE FUNCTION "booking_requests_holds_slot"();

-- ⑤ ADR-001's actual boundary.
--
-- Half-open '[)' — a slot ending 12:00 and one starting 12:00 do NOT overlap. This is the DB-level
-- half of the rule `booking-overlap.ts` states in TypeScript; the two must agree, and this literal is
-- the only place the DB says it.
--
-- `tsrange`, NOT `tstzrange`: "startAt"/"endAt" are `timestamp(3) without time zone` (Prisma's
-- default mapping) and `timestamp -> timestamptz` is STABLE, not IMMUTABLE, so a tstzrange form would
-- be REFUSED here. Prisma writes UTC into these columns, so every row is already on one scale.
--
-- `WHERE ("holdsSlot")` is what keeps overlapping PENDING requests legal (D-C13 rule 4): their rows
-- carry false and are never entered into the index at all.
--
-- ⚠️ There is no NOT VALID form of an EXCLUDE constraint. This builds and validates the index now,
-- holding ACCESS EXCLUSIVE for the duration. If it FAILS with 23P01 on an existing database, that
-- database already contains a real double booking — fix the data, never the constraint (R1).
-- Diagnostic:
--   SELECT a."id" AS a, b."id" AS b, a."venueId", a."startAt", b."startAt"
--     FROM "booking_slots" a JOIN "booking_slots" b
--       ON a."venueId" = b."venueId" AND a."id" < b."id"
--      AND tsrange(a."startAt", a."endAt", '[)') && tsrange(b."startAt", b."endAt", '[)')
--    WHERE a."holdsSlot" AND b."holdsSlot";
ALTER TABLE "booking_slots"
    ADD CONSTRAINT "booking_slots_no_overlap"
    EXCLUDE USING gist (
      "venueId"                         WITH =,
      tsrange("startAt", "endAt", '[)') WITH &&
    ) WHERE ("holdsSlot");
